openapi: 3.0.1
info:
  title: SquaresAPI
  description: Squares API
  version: '1.0'
tags:
  - name: Points
  - name: Squares
paths:
  /points:
    get:
      summary: Gets list of points.
      operationId: Points
      tags:
        - Points
      responses:
        '200':
          description: List of points
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PointsReply"
        '500':
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"

    post:
      summary: Add list of points.
      operationId: AddList
      tags:
        - Points
      requestBody:
        description: Point object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PointsReply"
            example:
              - XCoordinate: 0
                YCoordinate: 0
              - XCoordinate: 0
                YCoordinate: 1
              - XCoordinate: 1
                YCoordinate: 0
              - XCoordinate: 1
                YCoordinate: 1
              - XCoordinate: 1
                YCoordinate: 2
              - XCoordinate: 2
                YCoordinate: 1
              - XCoordinate: 2
                YCoordinate: 2

      responses:
        '201':
          description: List of points successfully added.
        '400':
          description: Data in the request was invalid or formatted incorrectly.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"
        '500':
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"

  /points/singlePoint:
    post:
      summary: Add new point.
      operationId: AddPoint
      tags:
        - Points
      requestBody:
        description: Point object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Point"
      responses:
        '201':
          description: Id of point that has been successfully added.
          content:
            application/json:
              schema:
                type: integer
        '400':
          description: Data in the request was invalid or formatted incorrectly.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"
        '500':
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"

  /points/singlePoint/{id}:
    delete:
      summary: Delete a point.
      operationId: Delete
      tags:
        - Points
      parameters:
        - in: path
          name: id
          description: Id of point to be deleted
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Point has been successfully deleted.
        '400':
          description: Data in the request was invalid or formatted incorrectly.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"
        '404':
          description: Provided point doesn't exist.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"

  /squares:
    get:
      summary: Gets list of possible squares.
      operationId: GetSquares
      tags:
        - Squares
      responses:
        '200':
          description: List of squares
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SquaresReply"
        '500':
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailureResponse"

components:
  schemas:
    PointsReply:
      description: Reply to points list request.
      type: array
      items:
        $ref: "#/components/schemas/Point"
      additionalProperties: false

    Point:
      description: Point object.
      type: object
      properties:
        id:
          type: integer
          nullable: true
        XCoordinate:
          type: integer
        YCoordinate:
          type: integer
      example:
        XCoordinate: -1
        YCoordinate: 3
      required:
        - XCoordinate
        - YCoordinate
      additionalProperties: false

    SquaresReply:
      description: Reply to list of squares request.
      type: array
      items:
        $ref: "#/components/schemas/Square"
      additionalProperties: false

    Square:
      description: Square angles.
      type: string
      example:
          '(0;0), (0;1), (1;0), (1;1)'
            '(0;1), (1;2), (1;0), (2;1)'
            '(1;1), (1;2), (2;1), (2;2)'

    FailureResponse:
      description: Response resource wrapping overall error and all the individual errors which occurred while processing request. Usually used with HTTP/4xx and HTTP/5xx status codes.
      type: object
      properties:
        code:
          description: Overall error code.
          type: integer
        message:
          description: Overall error message.
          type: string